---
title: "Pancancer_NK_atlas_Manuscript"
author: "Dillon Corvino"
date: "07/03/2019"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    theme: united
    highlight: tango
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

Built with R version `r getRversion()`

## Setup {.tabset}

### Dataset information
```{r Dataset_Info}

# Data downloaded from 
# https://zenodo.org/record/8275845


```

### Environment
```{r setup}

knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,  
  eval = TRUE, 
  tidy = TRUE
)

knitr::opts_knit$set(
  root.dir = "../"
)

# Environment Set up
rm(list = ls()) #Clean workspace
cat("\014")     #Clean Console
gc() # Free memory

# pipeline variables
long.compute <- FALSE

# Establish working directory
library("rstudioapi")

# Set working directory to source file location
setwd(dirname(getActiveDocumentContext()$path))
setwd("..")

# Create output directories & load custom functions & colour scheme
source("scripts/Setup.R", local = knitr::knit_global())
```

## Load data {.tabset}


### Read seurat files

```{r read_data}

nk.seurat <- LoadH5Seurat("data/pancancer_NK_atlas.h5seurat") #  data came from pancancer NK atlas github and is called "comb_CD56_CD16_NK.h5seurat"

# format metadata 
nk.seurat@meta.data <- nk.seurat@meta.data %>%
  mutate(tissue = ifelse(meta_tissue %in% c("Normal", "Others"), "non_tumor", as.character(meta_tissue)))

# restrict to just tumor-infiltrating cells
Idents(nk.seurat) <- nk.seurat@meta.data$tissue
tumor.seurat <- subset(nk.seurat, idents = "Tumor")

# reformat data because lack of certain groups now that just tumor cells 
colnames(tumor.seurat@meta.data)
table(tumor.seurat@meta.data$tissue)
table(tumor.seurat@meta.data$meta_tissue)
length(unique(tumor.seurat@meta.data$meta_patientID))

tumor.seurat@meta.data$celltype <- droplevels(tumor.seurat@meta.data$celltype)
tumor.seurat@meta.data$meta_tissue <- droplevels(tumor.seurat@meta.data$meta_tissue)
tumor.seurat@meta.data$meta_histology <- droplevels(tumor.seurat@meta.data$meta_histology)
tumor.seurat@meta.data$meta_patientID <- droplevels(tumor.seurat@meta.data$meta_patientID)

length(unique(tumor.seurat@meta.data$meta_patientID)) # 557 patients

rm(nk.seurat)

```



## Figure 5 and Supplementary Figure 2 {.tabset}


### Figure 5E and Supplementary Figure 2C - NKG7 expression
```{r Figure_5E_Sup_Figure_2C}

output.dir <- "results/figures/Figure_5/"
if(!dir.exists(output.dir)){
  dir.create(output.dir, 
             recursive = T)}




group.vec <- c("celltype", "Majortype", "meta_histology")


for(j in seq_along(group.vec)){
  
  print(
    VlnPlot_scCustom(tumor.seurat,
                     "NKG7",
                     group.by = group.vec[j],
                     pt.size = 0) + 
      NoLegend()
  )
  
  dev.copy(pdf, paste0(output.dir, "Vlnplot_NKG7_across_", group.vec[j], "_tumor_only.pdf"))
  dev.off()
}




```

### Figure 5F and Supplementary Figure 2D - cytotoxicity score scatter plots
```{r Figure_5F_Sup_Figure_2D}


output.dir <- "results/figures/Figure_5/"
if(!dir.exists(output.dir)){
  dir.create(output.dir, 
             recursive = T)}



# note doesnt change if integrated or RNA assay is used
DefaultAssay(tumor.seurat) <- "RNA"

table(tumor.seurat@meta.data$celltype)

Idents(tumor.seurat) <- tumor.seurat@meta.data$Majortype
pseudo.seurat <- AggregateExpression(tumor.seurat, 
                                     group.by = c("celltype"),
                                     return.seurat = TRUE)

goi <- list()

for(i in seq_along(cytotoxicity.markers)){
  goi[[i]] <- cytotoxicity.markers[-i]
  name.var <- paste0("cytotoxicity_minus_", cytotoxicity.markers[i])
  names(goi)[i] <- name.var
}

goi[[length(goi)+1]] <- cytotoxicity.markers
names(goi)[length(goi)] <- "Full_cytotoxicity_sig"



pseudo.seurat <- AddModuleScore(pseudo.seurat,
                                features = goi, 
                                name = names(goi))


end.point <- length(colnames(pseudo.seurat@meta.data))
start.point <- end.point-length(goi)
start.point <- start.point + 1
colnames(pseudo.seurat@meta.data)[start.point:end.point]


library(stringr)
string.var <- colnames(pseudo.seurat@meta.data)[start.point:end.point]
new_string <- str_remove(string.var, ".$")
colnames(pseudo.seurat@meta.data)[start.point:end.point] <- new_string


for(i in seq_along(goi)){
  if(names(goi)[i] == "Full_cytotoxicity_sig"){next}
  
  feature.1.var <- names(goi)[i]
  feature.2.var <- gsub("cytotoxicity_minus_", "", feature.1.var)
  
  print(
    scCustomize::FeatureScatter_scCustom(pseudo.seurat, 
                                         feature1 = feature.1.var,
                                         feature2 = feature.2.var,
                                         pt.size = 5,
                                         span = TRUE) + 
      scale_x_continuous(limits = c(0, 0.8)) + 
      NoLegend()
  )
  
  dev.copy(pdf, paste0(output.dir, "Cor_scatter_", feature.1.var, "_vs_", feature.2.var, "_tumor_only.pdf"))
  dev.off()
}


# for legend
scCustomize::FeatureScatter_scCustom(pseudo.seurat, 
                                     feature1 = feature.1.var,
                                     feature2 = feature.2.var,
                                     pt.size = 5,
                                     span = TRUE) + 
  scale_x_continuous(limits = c(0, 0.8))

dev.copy(pdf, paste0(output.dir, "Cor_scatter_", feature.1.var, "_vs_", feature.2.var, "_tumor_only_forlegend.pdf"))
dev.off()


```

