---
title: "Pancancer_NK_atlas"
author: "Dillon Corvino"
date: "07/03/2019"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    theme: united
    highlight: tango
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

Built with R version `r getRversion()`

## Setup {.tabset}

### Dataset information
```{r Dataset_Info}

# Data downloaded from 
# https://zenodo.org/record/8275845


```

### Environment
```{r setup}

knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,  
  eval = TRUE, 
  tidy = TRUE
)

knitr::opts_knit$set(
  root.dir = "../"
)

# Environment Set up
rm(list = ls()) #Clean workspace
cat("\014")     #Clean Console
gc() # Free memory

# pipeline variables
long.compute <- FALSE

# Establish working directory
library("rstudioapi")

# Set working directory to source file location
setwd(dirname(getActiveDocumentContext()$path))
setwd("..")

# Create output directories & load custom functions & colour scheme
source("scripts/Setup.R", local = knitr::knit_global())
```

## Load data {.tabset}


### Read seurat files

```{r read_data}

nk.seurat <- LoadH5Seurat("data/pancancer_NK_atlas.h5seurat") #  data came from pancancer NK atlas github and is called "comb_CD56_CD16_NK.h5seurat"

# format metadata 
nk.seurat@meta.data <- nk.seurat@meta.data %>%
  mutate(tissue = ifelse(meta_tissue %in% c("Normal", "Others"), "non_tumor", as.character(meta_tissue)))



```



## Dataset visualisation {.tabset}

### Generic overview of dataset
```{r dataset_overview}

output.dir <- "results/figures/Pancancer_NK_atlas/"
if(!dir.exists(output.dir)){
  dir.create(output.dir, 
             recursive = T)}




colnames(nk.seurat@meta.data)

meta.data.vars <- c("tissue", "Majortype", "celltype")

for(i in seq_along(meta.data.vars)){
  print(
    DimPlot_scCustom(nk.seurat, 
                     group.by = meta.data.vars[i],
                     raster = TRUE,
                     raster.dpi = c(2400, 2400),
                     label = TRUE,
                     pt.size = 4) + NoLegend()
  )
  dev.copy(pdf, paste0(output.dir, "UMAP_", meta.data.vars[i], ".pdf"))
  dev.off()
    
}

DimPlot_scCustom(nk.seurat, 
                 group.by = meta.data.vars[i],
                 raster = TRUE,
                 raster.dpi = c(2400, 2400),
                 label = TRUE,
                 pt.size = 4) 

dev.copy(pdf, paste0(output.dir, "UMAP_", meta.data.vars[i], "_for_legend.pdf"))
dev.off()


```


### visualise genes of interest
```{r vis_genes_of_interest}


output.dir <- "results/figures/Pancancer_NK_atlas_cytotoxic_genes/"
if(!dir.exists(output.dir)){
  dir.create(output.dir, 
             recursive = T)}


group.vec <- c("celltype", "meta_tissue", "tissue", "Majortype", "meta_histology")


for(i in seq_along(cytotoxicity.markers)){
  
  print(
    
    scCustomize::Plot_Density_Custom(nk.seurat, 
                                     features = cytotoxicity.markers[i], 
                                     custom_palette = batlow.pal)
  )
  
  ggsave(paste0(output.dir, "NK_Atlas_density_plot_", cytotoxicity.markers[i], ".tiff"),
         width = 12, height = 12, units = "in",
         device = "tiff", dpi = 320)
  
  


for(j in seq_along(group.vec)){
  
  print(
    VlnPlot_scCustom(nk.seurat,
                     cytotoxicity.markers[i],
                     group.by = group.vec[j],
                     pt.size = 0) + 
      NoLegend()
  )
  
  dev.copy(pdf, paste0(output.dir, "Vlnplot_", cytotoxicity.markers[i], "_across_", group.vec[i], ".pdf"))
  dev.off()
}


}


```


### visualise NKG7
```{r vis_NKG7}


output.dir <- "results/figures/Pancancer_NK_atlas_NKG7/"
if(!dir.exists(output.dir)){
  dir.create(output.dir, 
             recursive = T)}



group.vec <- c("celltype", "meta_tissue", "tissue", "Majortype", "meta_histology")

for(i in seq_along(group.vec)){
  
  print(
    VlnPlot_scCustom(nk.seurat,
                     "NKG7",
                     group.by = group.vec[i],
                     pt.size = 0) + 
      NoLegend()
  )
  
  dev.copy(pdf, paste0(output.dir, "Vlnplot_NKG7_across_", group.vec[i], ".pdf"))
  dev.off()
}





```



### cytotoxicity score scatter plots
```{r cytotoxicity_score_scatter_plots}


output.dir <- "results/figures/Pancancer_NK_atlas_correlation_scatters/"
if(!dir.exists(output.dir)){
  dir.create(output.dir, 
             recursive = T)}



# note doesnt change if integrated or RNA assay is used
DefaultAssay(nk.seurat) <- "RNA"

x <- nk.seurat@meta.data$tissue
y <- nk.seurat@meta.data$celltype
table(x, y)

Idents(nk.seurat) <- nk.seurat@meta.data$Majortype
pseudo.seurat <- AggregateExpression(nk.seurat, 
                                     group.by = c("celltype", "tissue"),
                                     return.seurat = TRUE)

goi <- list()

for(i in seq_along(cytotoxicity.markers)){
  goi[[i]] <- cytotoxicity.markers[-i]
  name.var <- paste0("cytotoxicity_minus_", cytotoxicity.markers[i])
  names(goi)[i] <- name.var
}

goi[[length(goi)+1]] <- cytotoxicity.markers
names(goi)[length(goi)] <- "Full_cytotoxicity_sig"



pseudo.seurat <- AddModuleScore(pseudo.seurat,
                                features = goi, 
                                name = names(goi))


end.point <- length(colnames(pseudo.seurat@meta.data))
start.point <- end.point-length(goi)
start.point <- start.point + 1
colnames(pseudo.seurat@meta.data)[start.point:end.point]


library(stringr)
string.var <- colnames(pseudo.seurat@meta.data)[start.point:end.point]
new_string <- str_remove(string.var, ".$")
colnames(pseudo.seurat@meta.data)[start.point:end.point] <- new_string


for(i in seq_along(goi)){
  if(names(goi)[i] == "Full_cytotoxicity_sig"){next}
  
  feature.1.var <- names(goi)[i]
  feature.2.var <- gsub("cytotoxicity_minus_", "", feature.1.var)
  
  print(
    scCustomize::FeatureScatter_scCustom(pseudo.seurat, 
                                         feature1 = feature.1.var,
                                         feature2 = feature.2.var,
                                         pt.size = 5,
                                         span = TRUE) + 
      scale_x_continuous(limits = c(0, 0.8)) + 
      NoLegend()
  )
  
  dev.copy(pdf, paste0(output.dir, "Cor_scatter_", feature.1.var, "_vs_", feature.2.var, ".pdf"))
  dev.off()
}


# for legend
scCustomize::FeatureScatter_scCustom(pseudo.seurat, 
                                     feature1 = feature.1.var,
                                     feature2 = feature.2.var,
                                     pt.size = 5,
                                     span = TRUE) + 
  scale_x_continuous(limits = c(0, 0.8))

dev.copy(pdf, paste0(output.dir, "Cor_scatter_", feature.1.var, "_vs_", feature.2.var, "_forlegend.pdf"))
dev.off()


```









```{r}






c("meta_histology", "tissue", "Majortype", "celltype")

nk.seurat@meta.data


# plot feature plots, Density plots, and vlnplots genes of interest

if(long.compute){
  
  
  # Gene expression on UMAP
  
  for(i in seq_along(goi)){
    
    # feature plot
    print(
      FeaturePlot_scCustom(nk.seurat, 
                           goi[i], 
                           pt.size = 0.5)
      
    )
    
    dev.copy(pdf, paste0(output.dir, "FeaturePlot_", goi[i], ".pdf"))
    dev.off()
    
    
    # density plot
    print(
      Plot_Density_Custom(nk.seurat, 
                          goi[i], 
                          custom_palette = batlow.pal)
    )
    dev.copy(pdf, paste0(output.dir, "Densityplot_", goi[i], ".pdf"))
    dev.off()
    
    
    
    
    # Plot signature across categories
    meta.data.vars <- c("meta_histology", "tissue", "Majortype", "celltype")
    
    for(j in seq_along(meta.data.vars)){
      print(
        VlnPlot_scCustom(nk.seurat,
                         goi[i], 
                         group.by = meta.data.vars[j],
                         pt.size = 0.1) + NoLegend()
      )
      dev.copy(pdf, paste0(output.dir, "VlnPlot_", goi[i], "_", meta.data.vars[j], ".pdf"))
      dev.off()
      
    }
  }
}






# write plotting function 

create_barplot <- function(contingency_table, plot_title, return_data = FALSE) {
  # Calculate percentages
  percentage_table <- sweep(contingency_table, 2, colSums(contingency_table), FUN = "/") * 100
  
  # Convert the result to a data frame
  percentage_df <- as.data.frame(percentage_table)
  
  # Filter rows where 'Var1' is TRUE
  filtered_df <- percentage_df %>%
    filter(Var1 == TRUE)
  
  # Calculate the average frequency
  average_freq <- mean(filtered_df$Freq)
  
  # Load the ggplot2 library
  library(ggplot2)
  
  # Create the barplot with ordered data
  plot <- ggplot(filtered_df, aes(x = reorder(Var2, -Freq), y = Freq)) +
    geom_col(fill = "#112446") +
    geom_hline(yintercept = average_freq, linetype = "dotted", color = "red") +  # Add a red dotted line
    labs(x = "Category", 
         y = "Frequency of each category", 
         title = plot_title) +  # Use the input plot_title
    coord_flip() +
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5))
  
  if (return_data) {
    return(filtered_df)
  } else {
    print(plot)
    return(NULL)
  }
}




# extract statistics and create barplots of score positive cell frequencies 

if(long.compute){
  
  for(i in seq_along(goi)){
    
    
    
    goi.expression <- nk.seurat@assays$RNA@data[goi[i], ]
    goi.logic <- goi.expression >= 0.5
    
    nk.seurat@meta.data$goistatus <- goi.logic
    
    
    
    meta.data.vars <- c("meta_histology", "tissue", "Majortype", "celltype")
    for(j in seq_along(meta.data.vars)){
      
      
      # Create a contingency table of 'sigstatus' and 'celltype'
      contingency_table <- table(nk.seurat@meta.data$goistatus, 
                                 nk.seurat@meta.data[[meta.data.vars[j]]])
      
      print(
        create_barplot(contingency_table, meta.data.vars[j])
      )
      
      dev.copy(pdf, paste0(output.dir, "Barplot_freq_of_cells_positive_for_", goi[i], "_across_", meta.data.vars[j], ".pdf"))
      dev.off()
      
      
      # export data
      output.dataframe <- create_barplot(contingency_table, meta.data.vars[j], return_data = TRUE)
      
      write.csv(output.dataframe, paste0(output.dir, "Freq_of_cells_positive_for_", goi[i], "_across_", meta.data.vars[j], ".csv"))
      
      
    }
    
    
  }
}


```

